---
- name: Install Java
  hosts: tag_NodeType_slave
  become: true

  vars:
    - ansible_ssh_private_key_file: "~/.ssh/aws_jenkins.pem"

  roles:
    - role: java_install


- name: Deploy Jeninks
  hosts: tag_NodeType_master
  become: true

  vars:
    - ansible_ssh_private_key_file: "~/.ssh/aws.pem"

  roles:
    - role: java_install
    - role: jenkins_deploy
